### ISSUE TITLE
KriosCoin

### ISSUE THREAD

**Issue by cristiansimion** [ExodusMovement/exodus-ethereum-tokens#21]
New ERC20 Token for Exodus:

- Token Address: 0xeef8102a0d46d508f171d7323bceffc592835f13
- URL to etherscan: https://etherscan.io/token/0xeef8102a0d46d508f171d7323bceffc592835f13
- URL to logo: https://www.krios.io/wp-content/uploads/2017/10/ic-1.png

**Comment by RyanZim** [comment]
Tokens must be on https://coinmarketcap.com/ before they can be considered for Exodus.
