### ISSUE TITLE
add imteaz(P)

### ISSUE THREAD

**Issue by imteazp** [ExodusMovement/exodus-ethereum-tokens#8]
New ERC20 Token for Exodus:

- Token Address: 0xa32b837dDF5859EeA664273b633b1cf47F1cDAf9
- URL to etherscan: https://etherscan.io/token/0xa32b837dDF5859EeA664273b633b1cf47F1cDAf9
- URL to logo: http://imteaz.ir/wp-content/uploads/2018/01/itz.png

**Comment by RyanZim** [comment]
Tokens must be on https://coinmarketcap.com/ before they can be considered for Exodus.
